version: "3"
services:

  webserver:
    hostname: webserver
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    ports:
    - "80:80"

  frontend:
    hostname: frontend
    image: cmcuritiba/extranet.cmcuritiba.pr.leg.br-frontend
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
    ports:
    - "3000:3000"
    depends_on:
      - backend

  backend:
    image: cmcuritiba/extranet.cmcuritiba.pr.leg.br-backend 
    hostname: backend
    environment:
      SITE: Plone
      RELSTORAGE_DSN: "dbname='plone' user='plone' host='db' password='plone'"
    ports:
      - "8080:8080"
    links:
      - db:db
    depends_on:
      - db

  db:
    image: postgres
    hostname: db
    environment:
      POSTGRES_USER: plone
      POSTGRES_PASSWORD: plone
      POSTGRES_DB: plone
    volumes:
    - data:/var/lib/postgresql/data
    ports:
    - "5432:5432"

volumes:
  data: {}
