version: "3"
services:

  webserver:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    ports:
    - "80:80"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
    ports:
    - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SITE: Plone
      RELSTORAGE_DSN: "dbname='plone' user='xxx' host='db' password='xxx'"
    ports:
    - "8080:8080"
    depends_on:
      - db


  db:
    image: postgres
    environment:
      POSTGRES_USER: xxx
      POSTGRES_PASSWORD: xxx
      POSTGRES_DB: plone
    volumes:
    - data:/var/lib/postgresql/data
    ports:
    - "5432:5432"

volumes:
  data: {}