---
# Dev
dev:
  hosts:
    extranet.cmcuritiba.pr.leg.br-local:
      ansible_host: 127.0.0.1
      ansible_ssh_port: 2222
      ansible_user: vagrant
      ansible_ssh_private_key_file: ./.vagrant_private_key
